name: Build Android APK

on:
  push:
    tags:
      - "v*"   # Déclenche sur les tags v1.0.0, v1.1.0, etc.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Installer Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Installer Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4️⃣ Build APK
      - name: Build APKs
        run: ./gradlew assembleRelease

      # 5️⃣ Créer la Release GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      # 6️⃣ Attacher tous les APKs générés dans la Release
      - name: Upload all APKs to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_url="${{ steps.create_release.outputs.upload_url }}"
          for apk in app/build/outputs/apk/release/*.apk; do
            echo "Uploading $apk..."
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/vnd.android.package-archive" \
              --data-binary @"$apk" \
              "${release_url}?name=$(basename $apk)"
          done
